name: AUR CI
on:
  push:
    branches: [ main ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Build Docker image."
        run: docker --debug build -t arch_repo .
      
      - name: "Run the Docker image."
        run: docker run arch_repo
      
      - name: "Copy repo to GitHub Actions disk."
        run: docker cp archlinux:/home/builduser/x86_64.tgz .
      
      - name: "Extract repo."
        run: tar -xvzf x86_64.tgz
      
      - name: "Deploy the repo."
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: x86_64    
