name: AUR CI
on:
  push:
    branches: [ main ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Build Docker image."
        uses: docker
        with:
          run: docker --debug build -t arch_repo .